/* Full landing-page copy for priority locales (merged in i18n.js) */
window.LANDING_PATCH = {
  tr: {
    meta_title: "Rabe3 Al-Quloob — Kur'an deneyiminiz, yeniden tasarlandı",
    meta_desc: "Kur'an'ı okuyun, ezberleyin ve yaşayın — sakin Mushaf, tilavet stüdyosu, günlük zikirler, çocuk modu ve gizlilik öncelikli tasarım. 28 dil.",
    brand_name: "Rabe3 Al-Quloob",
    nav_why: "Neden biz", nav_reader: "Okuyucu", nav_studio: "Stüdyo", nav_kids: "Çocuklar", nav_daily: "Günlük",
    nav_privacy: "Gizlilik", nav_download: "İndir",
    hero_eyebrow: "Kur'an uygulamaları için yeni bir standart",
    hero_headline: "Her zaman hayal ettiğiniz Kur'an deneyimi.",
    hero_sub: "Sükûnete dalın. Akıllı rehberlikle gelişin. Ailenizi Kitap'a yaklaştırın — reklam, gürültü veya taviz yok.",
    hero_b1: "Tefsir, ses ve on beş sakin temayla sürükleyici Mushaf",
    hero_b2: "Yargılamadan geliştirmenize yardımcı olan yapay zekâ destekli tilavet stüdyosu",
    hero_b3: "Güvenli çocuk dünyası ve günlük yoldaş — tasarımda gizlilik",
    hero_cta_primary: "Uygulamayı indir", hero_cta_secondary: "Nasıl çalıştığını gör",
    trust_no_ads: "Asla reklam yok", trust_privacy: "Gizlilik öncelikli", trust_offline: "Çevrimdışı çalışır", trust_family: "Aile için güvenli",
    mission_label: "Amacımız",
    mission_statement: "Allah'ın Kitabı ile ilişkinize sükûneti, güzelliği ve haysiyeti geri kazandırmak.",
    why_lead: "Çoğu uygulama dikkatinizi dağıtır. Okuma, hatırlama ve gelişim için tek bir sakin yuva tasarladık — ibadetinize yakışan bir onurla.",
    why_1_t: "Sükûnet için tasarlandı", why_1_d: "Her ekran nefes almanıza, odaklanmanıza ve ayette kalmanıza yardımcı olur — arayüzle savaşmanıza değil.",
    why_2_t: "Size hizmet eden zekâ", why_2_d: "Dinleyen, karşılaştıran ve koçluk yapan araçlar — gelişim doğal hissettirsin, bunaltıcı olmasın.",
    why_3_t: "Hissedebileceğiniz güven", why_3_d: "Reklam yok. Veri satışı yok. İlerlemeniz sizin — cihazınızda, kontrolünüz altında.",
    exp_read_eyebrow: "Okuma deneyimi", exp_read_title: "Mushaf'a kendinizi kaptırın.",
    exp_read_lead: "Kutsal ve modern hissettiren bir okuma alanı — her ayete ulaşmak, anlamak ve dönmek kolay.",
    exp_read_h1: "Güvenilir tefsir ve çevirilerle her ayeti anlayın",
    exp_read_h2: "Okurken güzel tilavetleri dinleyin",
    exp_read_h3: "Yer imi koyun, not alın, kaldığınız yerden devam edin",
    exp_read_h4: "Tüm Kur'an'da saniyeler içinde arayın",
    exp_read_cta: "Temaları keşfet",
    exp_studio_eyebrow: "Tilavet stüdyosu", exp_studio_title: "Sesinizi ayet ayet geliştirin.",
    exp_studio_lead: "Tecvid öğrencisi gibi çalışın — hocayı gölgeleyen, ilerlemenizi vurgulayan araçlarla.",
    exp_studio_h1: "Usta kârileri dinleyin, tekrarlayın ve gölgeleyin",
    exp_studio_h2: "Kendinizi kaydedin ve dalga formlarını yan yana karşılaştırın",
    exp_studio_h3: "Güven oluşturan akıllı geri bildirim alın",
    exp_studio_h4: "Hızınıza saygı duyan uyarlanabilir tekrarla ezberleyin",
    exp_studio_cta: "Pratiğe başla",
    exp_kids_eyebrow: "Çocuk macerası", exp_kids_title: "Çocuklarınızın Kur'an'ı sevmesine yardımcı olun.",
    exp_kids_lead: "Hikâyeler, yolculuklar ve ödüllerle dolu neşeli bir dünya — çocuklar için tasarlandı, ebeveynler tarafından korunuyor.",
    exp_kids_h1: "Canlı yolculuk haritasında adaları keşfedin ve yıldız kazanın",
    exp_kids_h2: "23 dilde hikâyeler ve eğlenceli masallar",
    exp_kids_h3: "Dinleyin, kaydedin ve kendilerini büyürken duyun",
    exp_kids_h4: "Ebeveyn PIN'i, ekran süresi ve kontrol ettiğiniz ilerleme",
    exp_daily_eyebrow: "Günlük yoldaş", exp_daily_title: "Gün boyunca bağlı kalın.",
    exp_daily_lead: "Fecirden uykuya — nazik hatırlatıcılar, sahih zikirler ve Kur'an'ı yakın tutan alışkanlıklar.",
    exp_daily_h1: "Gerçek hayat için düzenlenmiş 288 zikir ve 148 dua",
    exp_daily_h2: "Namaz vakitleri, kıble ve zikir sayacı tek yerde",
    exp_daily_h3: "Hatminizi takip edin ve tutarlı ilerlemeyi kutlayın",
    exp_daily_h4: "Aramalı Riyadü's-Salihin'den 1.896 hadis",
    exp_daily_cta: "Rutininizi oluşturun",
    section_privacy_eyebrow: "Gizlilik", section_privacy_title: "İbadetiniz size ait kalır.",
    section_privacy_desc: "Rabe3 Al-Quloob'u kutsal bir uygulamanın olması gerektiği gibi inşa ettik — saygı, şeffaflık ve verilerinizde sıfır taviz.",
    privacy_c1_t: "Varsayılan olarak cihazda", privacy_c1_d: "Yer imleri, notlar ve ilerleme telefonunuzda. Başlamak için hesap gerekmez.",
    privacy_c2_t: "Çocuklar korunuyor", privacy_c2_d: "Çocuk modu PIN korumalı, reklamsız ve gerçekten kullandığınız ebeveyn kontrolleriyle.",
    privacy_c3_t: "Mikrofon izninizle", privacy_c3_d: "Ses yalnızca pratik içindir — mümkün olduğunca cihazda işlenir, asla satılmaz.",
    section_themes_eyebrow: "Okuyucu temaları", section_themes_title: "Mushaf'ınız için on beş ruh hali.",
    section_themes_desc: "Altın şafaktan gece camisine — her tema okumayı dönmek istediğiniz bir deneyime dönüştürür.",
    theme_more_note: "Uygulamada 9 tema daha — burada 6 gösteriliyor.",
    section_premium_eyebrow: "Premium", section_premium_title: "Rabe3 Plus ile daha derine inin.",
    section_premium_desc: "Özel temalar, pratik klipleri için bulut senkronizasyonu, gelişmiş tecvid analizi ve aile özellikleri.",
    premium_p1: "Gece ve seyahat için özel okuyucu temaları",
    premium_p2: "Pratik klipleriniz ve ilerlemeniz için bulut yedekleme",
    premium_p3: "Yapay zekâ koçu ve derin tecvid içgörüleri",
    premium_cta: "Plus'ı keşfetmek için indirin",
    faq_eyebrow: "SSS", faq_title: "Sorularınız, yanıtlandı.",
    faq_q1: "Rabe3 Al-Quloob ücretsiz mi?", faq_a1: "Evet. Temel okuma, zikir, dua, hadis ve günlük araçlar ücretsiz. Premium gelişmiş temalar, bulut senkronizasyonu ve derin pratik özelliklerini açar.",
    faq_q2: "Çevrimdışı çalışır mı?", faq_a2: "Evet. Mushaf ve sesi indirerek internet olmadan okuyun ve dinleyin.",
    faq_q3: "Çocuklar için güvenli mi?", faq_a3: "Çocuk modu reklamsız, PIN korumalı ve ekran süresi ile profil kontrolleri içerir.",
    faq_q4: "Hangi diller destekleniyor?", faq_a4: "Tüm uygulama arayüzü 28 dilde mevcuttur — Arapça ve İngilizce'den Urduca, Türkçe, Çince ve daha fazlasına.",
    download_title: "Yolculuğunuza bugün başlayın.",
    download_lead: "Rabe3 Al-Quloob'u indirin — sakin, güzel ve Kur'an ile bir ömür için inşa edildi.",
    download_soon: "Google Play'de ücretsiz · Android",
    download_play_badge: "Google Play'den indir",
    play_badge_top: "İNDİRİN", play_badge_bottom: "Google Play",
    section_langs_eyebrow: "Küresel", section_langs_title: "28 dil. Tek yuva.",
    section_langs_desc: "Uygulamayı dilinize geçirin — Arapça'dan Çince, Türkçe, Urduca ve daha fazlasına 28 seçenek.",
    langs_landing_note: "Bu sayfa Arapça, İngilizce, Türkçe, Fransızca, Endonezce ve Urduca'da tam çevrilidir. Uygulama arayüzü 28 dili destekler.",
    langs_show_all: "Tüm 28 dili göster", langs_show_less: "Daha az göster",
    sticky_cta: "Uygulamayı indir",
    footer_privacy: "Gizlilik Politikası", footer_facebook: "Facebook'ta takip et", footer_contact: "Bize ulaşın",
    footer_tagline: "Allah çabalarımızı kabul etsin. © Rabe3 Al-Quloob",
    a11y_play_badge: "Google Play'den indir"
  },
  fr: {
    meta_title: "Rabe3 Al-Quloob — Votre Coran, magnifiquement réinventé",
    meta_desc: "Lisez, mémorisez et vivez avec le Coran — Mushaf serein, studio de récitation, adhkar quotidiens, mode enfants et design respectueux de la vie privée. 28 langues.",
    brand_name: "Rabe3 Al-Quloob",
    nav_why: "Pourquoi nous", nav_reader: "Lecture", nav_studio: "Studio", nav_kids: "Enfants", nav_daily: "Quotidien",
    nav_privacy: "Confidentialité", nav_download: "Télécharger",
    hero_eyebrow: "Une nouvelle référence pour les apps Coran",
    hero_headline: "L'expérience Coran que vous avez toujours souhaitée.",
    hero_sub: "Plongez dans le calme. Grandissez avec un accompagnement intelligent. Rapprochez votre famille du Livre — sans pubs, bruit ni compromis.",
    hero_b1: "Mushaf immersif avec tafsir, audio et quinze thèmes sereins",
    hero_b2: "Studio de récitation guidé par l'IA qui vous aide à progresser, sans juger",
    hero_b3: "Monde enfants sûr et compagnon quotidien — privé par conception",
    hero_cta_primary: "Télécharger l'app", hero_cta_secondary: "Voir comment ça marche",
    trust_no_ads: "Jamais de publicité", trust_privacy: "Vie privée d'abord", trust_offline: "Fonctionne hors ligne", trust_family: "Sûr pour la famille",
    mission_label: "Notre mission",
    mission_statement: "Redonner calme, beauté et dignité à votre relation avec le Livre d'Allah.",
    why_lead: "La plupart des apps dispersent votre attention. Nous avons conçu un seul foyer calme pour lire, mémoriser et grandir — avec la dignité que mérite votre adoration.",
    why_1_t: "Conçu pour le calme", why_1_d: "Chaque écran vous aide à respirer, vous concentrer et rester avec l'ayah — pas à lutter contre l'interface.",
    why_2_t: "Une intelligence au service", why_2_d: "Des outils qui écoutent, comparent et guident — pour que le progrès soit naturel, pas écrasant.",
    why_3_t: "Une confiance tangible", why_3_d: "Pas de pubs. Pas de vente de données. Votre progression reste la vôtre — sur votre appareil, sous votre contrôle.",
    exp_read_eyebrow: "Expérience de lecture", exp_read_title: "Perdez-vous dans le Mushaf.",
    exp_read_lead: "Un espace de lecture sacré et moderne — chaque verset est facile à atteindre, comprendre et retrouver.",
    exp_read_h1: "Comprenez chaque verset avec tafsir et traductions fiables",
    exp_read_h2: "Écoutez de belles récitations en lisant",
    exp_read_h3: "Signets, notes et reprise exacte où vous vous êtes arrêté",
    exp_read_h4: "Recherchez tout le Coran en quelques secondes",
    exp_read_cta: "Explorer les thèmes",
    exp_studio_eyebrow: "Studio de récitation", exp_studio_title: "Améliorez votre voix, ayah par ayah.",
    exp_studio_lead: "Entraînez-vous comme un élève en tajweed — avec des outils qui suivent le cheikh et guident votre prochaine étape.",
    exp_studio_h1: "Écoutez, répétez et suivez les maîtres récitateurs",
    exp_studio_h2: "Enregistrez-vous et comparez les formes d'onde",
    exp_studio_h3: "Recevez des retours intelligents qui renforcent la confiance",
    exp_studio_h4: "Mémorisez avec une révision adaptative à votre rythme",
    exp_studio_cta: "Commencer à pratiquer",
    exp_kids_eyebrow: "Aventure enfants", exp_kids_title: "Aidez vos enfants à aimer le Coran.",
    exp_kids_lead: "Un monde joyeux d'histoires, voyages et récompenses — conçu pour les enfants, protégé par les parents.",
    exp_kids_h1: "Explorez des îles et gagnez des étoiles sur une carte vivante",
    exp_kids_h2: "Histoires et contes amusants en 23 langues",
    exp_kids_h3: "Écoutez, enregistrez et entendez-vous grandir",
    exp_kids_h4: "Code PIN parental, temps d'écran et progression sous votre contrôle",
    exp_daily_eyebrow: "Compagnon quotidien", exp_daily_title: "Restez connecté tout au long de la journée.",
    exp_daily_lead: "Du Fajr au sommeil — rappels doux, adhkar authentiques et habitudes qui gardent le Coran proche.",
    exp_daily_h1: "288 adhkar et 148 invocations, organisés pour la vie réelle",
    exp_daily_h2: "Horaires de prière, Qibla et compteur de dhikr en un seul endroit",
    exp_daily_h3: "Suivez votre khatma et célébrez vos progrès constants",
    exp_daily_h4: "1 896 hadiths de Riyadh al-Salihin avec recherche",
    exp_daily_cta: "Construire votre routine",
    section_privacy_eyebrow: "Confidentialité", section_privacy_title: "Votre adoration reste la vôtre.",
    section_privacy_desc: "Nous avons construit Rabe3 Al-Quloob comme une app sacrée doit l'être — avec respect, transparence et zéro compromis sur vos données.",
    privacy_c1_t: "Sur l'appareil par défaut", privacy_c1_d: "Signets, notes et progression sur votre téléphone. Aucun compte requis pour commencer.",
    privacy_c2_t: "Enfants protégés", privacy_c2_d: "Le mode enfants est protégé par PIN, sans pub, avec des contrôles parentaux utiles.",
    privacy_c3_t: "Microphone avec consentement", privacy_c3_d: "L'audio est uniquement pour la pratique — traité sur l'appareil quand possible, jamais vendu.",
    section_themes_eyebrow: "Thèmes de lecture", section_themes_title: "Quinze ambiances pour votre Mushaf.",
    section_themes_desc: "De l'aube dorée à la mosquée de minuit — chaque thème transforme la lecture en expérience à laquelle on revient.",
    theme_more_note: "9 thèmes supplémentaires dans l'app — 6 affichés ici.",
    section_premium_eyebrow: "Premium", section_premium_title: "Allez plus loin avec Rabe3 Plus.",
    section_premium_desc: "Thèmes exclusifs, sync cloud pour les clips, analyse tajweed avancée et fonctionnalités familiales.",
    premium_p1: "Thèmes de lecture exclusifs pour la nuit et les voyages",
    premium_p2: "Sauvegarde cloud de vos clips et progression",
    premium_p3: "Coach IA et analyses tajweed approfondies",
    premium_cta: "Télécharger pour explorer Plus",
    faq_eyebrow: "FAQ", faq_title: "Vos questions, nos réponses.",
    faq_q1: "Rabe3 Al-Quloob est-il gratuit ?", faq_a1: "Oui. Lecture, adhkar, dua, hadith et outils quotidiens sont gratuits. Premium débloque thèmes avancés, sync cloud et pratique approfondie.",
    faq_q2: "Fonctionne-t-il hors ligne ?", faq_a2: "Oui. Téléchargez Mushaf et audio pour lire et écouter sans connexion.",
    faq_q3: "Est-ce sûr pour les enfants ?", faq_a3: "Le mode enfants est sans pub, protégé par PIN, avec contrôles parentaux.",
    faq_q4: "Quelles langues sont supportées ?", faq_a4: "L'interface complète est disponible en 28 langues — de l'arabe et l'anglais à l'ourdou, le turc, le chinois et plus.",
    download_title: "Commencez votre voyage aujourd'hui.",
    download_lead: "Téléchargez Rabe3 Al-Quloob — calme, beau et conçu pour une vie avec le Coran.",
    download_soon: "Gratuit sur Google Play · Android",
    download_play_badge: "Disponible sur Google Play",
    play_badge_top: "DISPONIBLE SUR", play_badge_bottom: "Google Play",
    section_langs_eyebrow: "Mondial", section_langs_title: "28 langues. Un seul foyer.",
    section_langs_desc: "Passez l'app dans votre langue — 28 options de l'arabe au chinois, turc, ourdou et plus.",
    langs_landing_note: "Cette page est entièrement traduite en arabe, anglais, turc, français, indonésien et ourdou. L'app prend en charge 28 langues.",
    langs_show_all: "Afficher les 28 langues", langs_show_less: "Afficher moins",
    sticky_cta: "Télécharger l'app",
    footer_privacy: "Politique de confidentialité", footer_facebook: "Suivre sur Facebook", footer_contact: "Nous contacter",
    footer_tagline: "Qu'Allah accepte nos efforts. © Rabe3 Al-Quloob",
    a11y_play_badge: "Disponible sur Google Play"
  },
  id: {
    meta_title: "Rabe3 Al-Quloob — Al-Quran Anda, dirancang ulang dengan indah",
    meta_desc: "Baca, hafal, dan hidup dengan Al-Quran — Mushaf tenang, studio tilawah, dzikir harian, mode anak, dan desain yang mengutamakan privasi. 28 bahasa.",
    brand_name: "Rabe3 Al-Quloob",
    nav_why: "Mengapa kami", nav_reader: "Pembaca", nav_studio: "Studio", nav_kids: "Anak", nav_daily: "Harian",
    nav_privacy: "Privasi", nav_download: "Unduh",
    hero_eyebrow: "Standar baru untuk aplikasi Al-Quran",
    hero_headline: "Pengalaman Al-Quran yang selalu Anda impikan.",
    hero_sub: "Tenggelam dalam ketenangan. Berkembang dengan bimbingan cerdas. Dekatkan keluarga Anda pada Kitab — tanpa iklan, kebisingan, atau kompromi.",
    hero_b1: "Mushaf imersif dengan tafsir, audio, dan lima belas tema yang tenang",
    hero_b2: "Studio tilawah berbantuan AI yang membantu Anda berkembang, bukan menghakimi",
    hero_b3: "Dunia anak yang aman dan teman harian — privat by design",
    hero_cta_primary: "Unduh aplikasi", hero_cta_secondary: "Lihat cara kerjanya",
    trust_no_ads: "Tanpa iklan, selamanya", trust_privacy: "Privasi utama", trust_offline: "Bekerja offline", trust_family: "Aman untuk keluarga",
    mission_label: "Tujuan kami",
    mission_statement: "Mengembalikan ketenangan, keindahan, dan martabat pada hubungan Anda dengan Kitab Allah.",
    why_lead: "Kebanyakan aplikasi menyebarkan perhatian Anda. Kami merancang satu rumah tenang untuk membaca, mengingat, dan berkembang — dengan martabat yang layak untuk ibadah Anda.",
    why_1_t: "Dirancang untuk ketenangan", why_1_d: "Setiap layar dibuat agar Anda bernapas, fokus, dan tetap dengan ayat — bukan melawan antarmuka.",
    why_2_t: "Kecerdasan yang melayani Anda", why_2_d: "Alat yang mendengarkan, membandingkan, dan membimbing — agar perkembangan terasa alami.",
    why_3_t: "Kepercayaan yang terasa", why_3_d: "Tanpa iklan. Tanpa penjualan data. Kemajuan Anda milik Anda — di perangkat Anda, di bawah kendali Anda.",
    exp_read_eyebrow: "Pengalaman membaca", exp_read_title: "Tenggelam dalam Mushaf.",
    exp_read_lead: "Ruang baca yang terasa sakral dan modern — setiap ayat mudah dijangkau, dipahami, dan dikunjungi kembali.",
    exp_read_h1: "Pahami setiap ayat dengan tafsir dan terjemahan terpercaya",
    exp_read_h2: "Dengarkan tilawah indah sambil membaca",
    exp_read_h3: "Penanda, catatan, dan lanjutkan tepat di tempat Anda berhenti",
    exp_read_h4: "Cari seluruh Al-Quran dalam hitungan detik",
    exp_read_cta: "Jelajahi tema",
    exp_studio_eyebrow: "Studio tilawah", exp_studio_title: "Perbaiki suara Anda, ayat demi ayat.",
    exp_studio_lead: "Latih seperti murid tajwid — dengan alat yang mengikuti syekh dan memandu langkah berikutnya.",
    exp_studio_h1: "Dengarkan, ulangi, dan ikuti qari master",
    exp_studio_h2: "Rekam diri Anda dan bandingkan gelombang suara",
    exp_studio_h3: "Dapatkan umpan balik cerdas yang membangun kepercayaan diri",
    exp_studio_h4: "Hafal dengan ulasan adaptif yang menghormati kecepatan Anda",
    exp_studio_cta: "Mulai berlatih",
    exp_kids_eyebrow: "Petualangan anak", exp_kids_title: "Bantu anak-anak Anda mencintai Al-Quran.",
    exp_kids_lead: "Dunia cerita, perjalanan, dan hadiah yang menyenangkan — dirancang untuk anak, dilindungi orang tua.",
    exp_kids_h1: "Jelajahi pulau dan kumpulkan bintang di peta perjalanan hidup",
    exp_kids_h2: "Cerita dan dongeng menyenangkan dalam 23 bahasa",
    exp_kids_h3: "Dengarkan, rekam, dan dengar diri mereka berkembang",
    exp_kids_h4: "PIN orang tua, waktu layar, dan kemajuan yang Anda kendalikan",
    exp_daily_eyebrow: "Teman harian", exp_daily_title: "Tetap terhubung sepanjang hari.",
    exp_daily_lead: "Dari Subuh hingga tidur — pengingat lembut, dzikir otentik, dan kebiasaan yang menjaga Al-Quran dekat.",
    exp_daily_h1: "288 dzikir dan 148 doa, diatur untuk kehidupan nyata",
    exp_daily_h2: "Waktu sholat, Kiblat, dan penghitung dzikir dalam satu tempat",
    exp_daily_h3: "Lacak khatam Anda dan rayakan kemajuan konsisten",
    exp_daily_h4: "1.896 hadis dari Riyadh al-Salihin dengan pencarian",
    exp_daily_cta: "Bangun rutinitas Anda",
    section_privacy_eyebrow: "Privasi", section_privacy_title: "Ibadah Anda tetap milik Anda.",
    section_privacy_desc: "Kami membangun Rabe3 Al-Quloob seperti aplikasi suci seharusnya — dengan hormat, transparansi, dan tanpa kompromi data Anda.",
    privacy_c1_t: "Di perangkat secara default", privacy_c1_d: "Penanda, catatan, dan kemajuan di ponsel Anda. Tidak perlu akun untuk memulai.",
    privacy_c2_t: "Anak-anak dilindungi", privacy_c2_d: "Mode anak dilindungi PIN, bebas iklan, dengan kontrol orang tua yang benar-benar digunakan.",
    privacy_c3_t: "Mikrofon dengan izin", privacy_c3_d: "Audio hanya untuk latihan — diproses di perangkat jika memungkinkan, tidak pernah dijual.",
    section_themes_eyebrow: "Tema pembaca", section_themes_title: "Lima belas suasana untuk Mushaf Anda.",
    section_themes_desc: "Dari fajar emas hingga masjid tengah malam — setiap tema mengubah membaca menjadi pengalaman yang ingin Anda kembali.",
    theme_more_note: "9 tema lagi di dalam aplikasi — 6 ditampilkan di sini.",
    section_premium_eyebrow: "Premium", section_premium_title: "Lebih dalam dengan Rabe3 Plus.",
    section_premium_desc: "Tema eksklusif, sinkronisasi cloud untuk klip latihan, analisis tajwid lanjutan, dan fitur keluarga.",
    premium_p1: "Tema pembaca eksklusif untuk malam dan perjalanan",
    premium_p2: "Cadangan cloud untuk klip latihan dan kemajuan Anda",
    premium_p3: "Pelatih AI dan wawasan tajwid mendalam",
    premium_cta: "Unduh untuk menjelajahi Plus",
    faq_eyebrow: "FAQ", faq_title: "Pertanyaan, terjawab.",
    faq_q1: "Apakah Rabe3 Al-Quloob gratis?", faq_a1: "Ya. Membaca inti, dzikir, doa, hadis, dan alat harian gratis. Premium membuka tema lanjutan, sinkronisasi cloud, dan fitur latihan lebih dalam.",
    faq_q2: "Apakah berfungsi offline?", faq_a2: "Ya. Unduh Mushaf dan audio untuk membaca dan mendengarkan tanpa internet.",
    faq_q3: "Apakah aman untuk anak-anak?", faq_a3: "Mode anak bebas iklan, dilindungi PIN, dengan kontrol waktu layar dan profil.",
    faq_q4: "Bahasa apa yang didukung?", faq_a4: "Seluruh antarmuka aplikasi tersedia dalam 28 bahasa — dari Arab dan Inggris hingga Urdu, Turki, Mandarin, dan lainnya.",
    download_title: "Mulai perjalanan Anda hari ini.",
    download_lead: "Unduh Rabe3 Al-Quloob — tenang, indah, dan dibangun untuk seumur hidup dengan Al-Quran.",
    download_soon: "Gratis di Google Play · Android",
    download_play_badge: "Dapatkan di Google Play",
    play_badge_top: "DAPATKAN DI", play_badge_bottom: "Google Play",
    section_langs_eyebrow: "Global", section_langs_title: "28 bahasa. Satu rumah.",
    section_langs_desc: "Ganti bahasa aplikasi — 28 pilihan dari Arab hingga Mandarin, Turki, Urdu, dan lainnya.",
    langs_landing_note: "Halaman ini diterjemahkan penuh dalam Arab, Inggris, Turki, Prancis, Indonesia, dan Urdu. Aplikasi mendukung 28 bahasa.",
    langs_show_all: "Tampilkan semua 28 bahasa", langs_show_less: "Tampilkan lebih sedikit",
    sticky_cta: "Unduh aplikasi",
    footer_privacy: "Kebijakan Privasi", footer_facebook: "Ikuti di Facebook", footer_contact: "Hubungi kami",
    footer_tagline: "Semoga Allah menerima usaha kami. © Rabe3 Al-Quloob",
    a11y_play_badge: "Dapatkan di Google Play"
  },
  ur: {
    meta_title: "ربيع القلوب — آپ کا قرآن، خوبصورتی سے دوبارہ تصور شدہ",
    meta_desc: "قرآن پڑھیں، حفظ کریں اور زندگی گزاریں — پرسکون مصحف، تلاوت اسٹوڈیو، روزانہ اذکار، بچوں کا موڈ، اور پرائیویسی پہلے۔ ۲۸ زبانیں۔",
    brand_name: "ربيع القلوب",
    nav_why: "کیوں ہم", nav_reader: "قاری", nav_studio: "اسٹوڈیو", nav_kids: "بچے", nav_daily: "روزانہ",
    nav_privacy: "رازداری", nav_download: "ڈاؤن لوڈ",
    hero_eyebrow: "قرآن ایپس کے لیے نیا معیار",
    hero_headline: "وہ قرآنی تجربہ جو آپ ہمیشہ چاہتے تھے۔",
    hero_sub: "سکون میں ڈوب جائیں۔ ذہین رہنمائی سے بڑھیں۔ اپنے خاندان کو کتاب کے قریب لائیں — بغیر اشتہارات، شور یا سمجھوتے کے۔",
    hero_b1: "تفسیر، آڈیو اور پندرہ پرسکون تھیمز کے ساتھ گہرا مصحف",
    hero_b2: "اے آئی سے رہنمائی شدہ تلاوت اسٹوڈیو جو بہتر بناتا ہے، نہیں جج کرتا",
    hero_b3: "محفوظ بچوں کی دنیا اور روزانہ ساتھی — ڈیزائن میں رازداری",
    hero_cta_primary: "ایپ حاصل کریں", hero_cta_secondary: "کیسے کام کرتا ہے دیکھیں",
    trust_no_ads: "کبھی اشتہار نہیں", trust_privacy: "رازداری پہلے", trust_offline: "آف لائن کام کرتا ہے", trust_family: "خاندان کے لیے محفوظ",
    mission_label: "ہمارا مقصد",
    mission_statement: "اللہ کی کتاب سے آپ کے تعلق میں سکون، خوبصورتی اور وقار بحال کرنا۔",
    why_lead: "زیادہ تر ایپس آپ کی توجہ بکھیر دیتی ہیں۔ ہم نے پڑھنے، یاد رکھنے اور بڑھنے کے لیے ایک پرسکون گھر بنایا — عبادت کی عزت کے ساتھ۔",
    why_1_t: "سکون کے لیے بنایا گیا", why_1_d: "ہر اسکرین سانس لینے، توجہ مرکوز کرنے اور آیت کے ساتھ رہنے میں مدد کرتی ہے — انٹرفیس سے لڑنے میں نہیں۔",
    why_2_t: "ذہانت جو آپ کی خدمت کرے", why_2_d: "سننے، موازنہ کرنے اور رہنمائی کرنے والے ٹولز — بہتری قدرتی محسوس ہو۔",
    why_3_t: "قابلِ احساس اعتماد", why_3_d: "کوئی اشتہار نہیں۔ ڈیٹا فروخت نہیں۔ آپ کی پیشرفت آپ کی ہے — آپ کے ڈیوائس پر، آپ کے کنٹرول میں۔",
    exp_read_eyebrow: "پڑھنے کا تجربہ", exp_read_title: "مصحف میں کھو جائیں۔",
    exp_read_lead: "مقدس اور جدید پڑھنے کی جگہ — ہر آیت تک پہنچنا، سمجھنا اور واپس آنا آسان۔",
    exp_read_h1: "قابلِ اعتماد تفسیر اور ترجمے سے ہر آیت سمجھیں",
    exp_read_h2: "پڑھتے ہوئے خوبصورت تلاوتیں سنیں",
    exp_read_h3: "بک مارک، نوٹ اور جہاں چھوڑا وہیں سے شروع کریں",
    exp_read_h4: "سیکنڈوں میں پورے قرآن میں تلاش کریں",
    exp_read_cta: "تھیمز دیکھیں",
    exp_studio_eyebrow: "تلاوت اسٹوڈیو", exp_studio_title: "آیت بہ آیت اپنی آواز بہتر بنائیں۔",
    exp_studio_lead: "تجوید کے طالب علم کی طرح مشق کریں — شیخ کے ساتھ سایہ کرنے والے ٹولز کے ساتھ۔",
    exp_studio_h1: "ماہر قاریوں کو سنیں، دہرائیں اور سایہ کریں",
    exp_studio_h2: "اپنی آواز ریکارڈ کریں اور لہروں کا موازنہ کریں",
    exp_studio_h3: "اعتماد بڑھانے والی ذہین رائے حاصل کریں",
    exp_studio_h4: "اپنی رفتار کا احترام کرنے والی جائزے سے حفظ کریں",
    exp_studio_cta: "مشق شروع کریں",
    exp_kids_eyebrow: "بچوں کی مہم", exp_kids_title: "اپنے بچوں کو قرآن سے محبت کروائیں۔",
    exp_kids_lead: "کہانیوں، سفر اور انعامات کی خوشی بھری دنیا — بچوں کے لیے، والدین سے محفوظ۔",
    exp_kids_h1: "زندہ سفر کے نقشے پر جزیرے دریافت کریں اور ستارے جمع کریں",
    exp_kids_h2: "۲۳ زبانوں میں کہانیاں اور مزے دار افسانے",
    exp_kids_h3: "سنیں، ریکارڈ کریں اور خود کو بڑھتے ہوئے سنیں",
    exp_kids_h4: "والدین کا PIN، اسکرین ٹائم اور آپ کے کنٹرول میں پیشرفت",
    exp_daily_eyebrow: "روزانہ ساتھی", exp_daily_title: "پورے دن جڑے رہیں۔",
    exp_daily_lead: "فجر سے نیند تک — نرم یاددہانیاں، مستند اذکار اور قرآن قریب رکھنے والی عادات۔",
    exp_daily_h1: "حقیقی زندگی کے لیے ترتیب شدہ ۲۸۸ اذکار اور ۱۴۸ دعائیں",
    exp_daily_h2: "نماز کے اوقات، قبلہ اور ذکر کاؤنٹر ایک جگہ",
    exp_daily_h3: "اپنی ختمہ ٹریک کریں اور مستقل پیشرفت منائیں",
    exp_daily_h4: "تلاش کے ساتھ ریاض الصالحین سے ۱,۸۹۶ احادیث",
    exp_daily_cta: "اپنی روٹین بنائیں",
    section_privacy_eyebrow: "رازداری", section_privacy_title: "آپ کی عبادت آپ کی رہے۔",
    section_privacy_desc: "ہم نے ربيع القلوب کو مقدس ایپ کی طرح بنایا — احترام، شفافیت اور آپ کے ڈیٹا پر کوئی سمجھوتہ نہیں۔",
    privacy_c1_t: "ڈیفالٹ پر ڈیوائس پر", privacy_c1_d: "بک مارک، نوٹ اور پیشرفت آپ کے فون پر۔ شروع کرنے کے لیے اکاؤنٹ نہیں چاہیے۔",
    privacy_c2_t: "بچے محفوظ", privacy_c2_d: "بچوں کا موڈ PIN سے محفوظ، بغیر اشتہار، والدین کے کنٹرولز کے ساتھ۔",
    privacy_c3_t: "رضامندی سے مائیکروفون", privacy_c3_d: "آڈیو صرف مشق کے لیے — جہاں ممکن ہو ڈیوائس پر، کبھی فروخت نہیں۔",
    section_themes_eyebrow: "قاری تھیمز", section_themes_title: "آپ کے مصحف کے لیے پندرہ موڈز۔",
    section_themes_desc: "سنہری فجر سے آدھی رات کی مسجد تک — ہر تھیم پڑھنے کو واپس آنے والا تجربہ بناتا ہے۔",
    theme_golden: "سنہری فجر", theme_midnight: "آدھی رات کی مسجد", theme_emerald: "زمرد جنت",
    theme_ottoman: "عثمانی نیلا", theme_neon: "نیون مکہ", theme_sakura: "ساکورا مسجد",
    theme_more_note: "ایپ میں ۹ تھیمز مزید — یہاں ۶ دکھائے گئے۔",
    section_premium_eyebrow: "پریمیم", section_premium_title: "ربيع پلس کے ساتھ گہرے جائیں۔",
    section_premium_desc: "خصوصی تھیمز، مشق کلپس کے لیے کلاؤڈ سنک، جدید تجوید تجزیہ اور خاندانی خصوصیات۔",
    premium_p1: "رات اور سفر کے لیے خصوصی قاری تھیمز",
    premium_p2: "مشق کلپس اور پیشرفت کے لیے کلاؤڈ بیک اپ",
    premium_p3: "اے آئی کوچ اور گہرے تجوید بصیرت",
    premium_cta: "پلس دریافت کرنے کے لیے ڈاؤن لوڈ کریں",
    faq_eyebrow: "سوالات", faq_title: "سوالات، جوابات۔",
    faq_q1: "کیا ربيع القلوب مفت ہے؟", faq_a1: "جی ہاں۔ بنیادی پڑھنا، اذکار، دعا، احادیث اور روزانہ ٹولز مفت ہیں۔ پریمیم جدید تھیمز، کلاؤڈ سنک اور گہری مشق کی خصوصیات کھولتا ہے۔",
    faq_q2: "کیا آف لائن کام کرتا ہے؟", faq_a2: "جی ہاں۔ مصحف اور آڈیو ڈاؤن لوڈ کریں بغیر انٹرنیٹ پڑھنے اور سننے کے لیے۔",
    faq_q3: "کیا بچوں کے لیے محفوظ ہے؟", faq_a3: "بچوں کا موڈ بغیر اشتہار، PIN سے محفوظ، اسکرین ٹائم اور پروفائل کنٹرولز کے ساتھ۔",
    faq_q4: "کون سی زبانیں سپورٹ ہیں؟", faq_a4: "پوری ایپ انٹرفیس ۲۸ زبانوں میں — عربی اور انگریزی سے اردو، ترکی، چینی اور مزید۔",
    download_title: "آج اپنی سفر شروع کریں۔",
    download_lead: "ربيع القلوب ڈاؤن لوڈ کریں — پرسکون، خوبصورت، اور قرآن کے ساتھ زندگی بھر کے لیے۔",
    download_soon: "Google Play پر مفت · Android",
    download_play_badge: "Google Play سے حاصل کریں",
    play_badge_top: "یہاں سے حاصل کریں", play_badge_bottom: "Google Play",
    section_langs_eyebrow: "عالمی", section_langs_title: "۲۸ زبانیں۔ ایک گھر۔",
    section_langs_desc: "ایپ اپنی زبان میں بدلیں — عربی سے چینی، ترکی، اردو اور مزید تک ۲۸ اختیارات۔",
    langs_landing_note: "یہ صفحہ عربی، انگریزی، ترکی، فرانسیسی، انڈونیشیائی اور اردو میں مکمل ترجمہ شدہ ہے۔ ایپ ۲۸ زبانیں سپورٹ کرتی ہے۔",
    langs_show_all: "تمام ۲۸ زبانیں دکھائیں", langs_show_less: "کم دکھائیں",
    sticky_cta: "ایپ حاصل کریں",
    footer_privacy: "رازداری کی پالیسی", footer_facebook: "فیس بک پر فالو کریں", footer_contact: "رابطہ",
    footer_tagline: "اللہ ہماری کوششیں قبول فرمائے۔ © ربيع القلوب",
    a11y_play_badge: "Google Play سے حاصل کریں"
  }
};
